name = "download-station"
main = "src/backend/index.js"
compatibility_date = "2023-01-01"

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "download_station_db"
database_id = "dcfe28e4-2e87-46ac-a872-edc842c1a342" # 部署时需替换为实际的数据库ID